version: '3'

services:
  fpl-app:
    build: .
    depends_on:
      - selenium
    environment:
      - SE_EVENT_BUS_HOST=selenium

  selenium:
    image: selenium/standalone-firefox:latest
    shm_size: 2g
    ports:
      - "4447:4444" # Selenium Grid
      - "7905:7900" # noVNC for viewing browser